apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealership
  template:
    metadata:
      labels:
        app: dealership
    spec:
      containers:
      - name: dealership
        image: us.icr.io/sn-labs-abassaliabas/dealership:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dealership
spec:
  selector:
    app: dealership
  ports:
  - port: 8000
    targetPort: 8000
